title = "This is awesome 🚀"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Indlæg"
    url = "/posts"
    weight = 10

  [[menu.main]]
    identifier = "about"
    name = "Om os!"
    url = "/about"
    weight = 20
